### ISSUE TITLE
Unable to update chat message.

### ISSUE THREAD

**Issue by gaurav2493** [slackapi/java-slack-sdk#372]
### Issue Type

- [x] Bug
- [ ] Enhancement / Feature request
- [ ] Question
- [ ] Documentation

### Description

Request to update chat message is failing
---
(only for a bug report)

**TODO**:
If this is a bug report, filling out the following details about bugs will help us solve your issue sooner.

The issue is reproducible in:
* Module Version: 0.99.2
* JDK Version: 1.8.0_231
* OS Version etc: Mac OS 10.15.3 (19D76)

The steps to reproduce are:

1. Create request
```
val request = ChatUpdateRequest.builder()
                        .token(eventContext.botToken)
                        .text("text")
                        .channel(payloadAction.selectedChannel)
                        .ts(timeStamp).build()
```
2. Send Update Request
```
ctx.slack.methods().chatUpdate(request)
```

The expected result is:
Chat message to be updated

The actual result is:
```
{"ok":false,"error":"invalid_arguments","deprecated_argument":"as_user"}
```
---

### Requirements

* [x] I've read and understood the [Contributing guidelines](https://github.com/slackapi/java-slack-sdk/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

**Comment by seratch** [comment]
@gaurav2493 Thank you for reporting this issue. I verified this issue occurs with Granular Permissions.  I mistakenly have been running all the unit tests with the real APIs using a token with classic app permissions. I will fix this and release a new milestone version as soon as possible.

**Comment by seratch** [comment]
@gaurav2493 
Thank you very much for reporting this. I really appreciate it.
I've revisited all the unit tests, improved them, and fixed the bug and a few similar.

I just released a new version `1.0.0-M2` including those fixes. Could you try it out when you have a chance? Thanks again for your great help!

**Comment by gaurav2493** [comment]
> @gaurav2493
> Thank you very much for reporting this. I really appreciate it.
> I've revisited all the unit tests, improved them, and fixed the bug and a few similar.
> 
> I just released a new version `1.0.0-M2` including those fixes. Could you try it out when you have a chance? Thanks again for your great help!

Thanks @seratch for fixing this fast. Yes I have verified, its working.

**Comment by gvsakhil** [comment]
I am still facing this issue

{
    "ok": false,
    "error": "invalid_arguments",
    "deprecated_argument": "as_user",
    "warning": "missing_charset",
    "response_metadata": {
        "warnings": [
            "missing_charset"
        ]
    }
}

**Comment by gvsakhil** [comment]
I went through the docs and for new bots we can use just the bot accessToken directly and we can ignore as_user parameter. It should we working fine with this 👍 

Example:

```
const config = {
          method: 'post',
          url: 'https://slack.com/api/chat.postMessage',
          data: {
            token: token,
            channel: event.channel,
            text: 'These are the blocks'
          },
          headers: { 'Authorization': 'Bearer botToken' }
        }

        const response = await axios(config);
```
